// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg0-LGqC2bRdgbbeld_uDOp89Y5CG19Vk',
    appId: '1:106631481866:web:e6d7c2f63fdfb9e6c8adf3',
    messagingSenderId: '106631481866',
    projectId: 'nikeapp-13704',
    authDomain: 'nikeapp-13704.firebaseapp.com',
    storageBucket: 'nikeapp-13704.firebasestorage.app',
    measurementId: 'G-HNG2XMSVT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMioWVFj6wcUfZ5T03x0rK8hi3L5x52S8',
    appId: '1:106631481866:android:c3d90e03697c7c4fc8adf3',
    messagingSenderId: '106631481866',
    projectId: 'nikeapp-13704',
    storageBucket: 'nikeapp-13704.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRmnc3dIozt-MTLivY6CvDZscNZhpS3KI',
    appId: '1:106631481866:ios:4f255eaae34a12fdc8adf3',
    messagingSenderId: '106631481866',
    projectId: 'nikeapp-13704',
    storageBucket: 'nikeapp-13704.firebasestorage.app',
    iosClientId: '106631481866-ntvj14io9dr3gg6dc2ongauocj1vnr2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.nikeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRmnc3dIozt-MTLivY6CvDZscNZhpS3KI',
    appId: '1:106631481866:ios:4f255eaae34a12fdc8adf3',
    messagingSenderId: '106631481866',
    projectId: 'nikeapp-13704',
    storageBucket: 'nikeapp-13704.firebasestorage.app',
    iosClientId: '106631481866-ntvj14io9dr3gg6dc2ongauocj1vnr2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.nikeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg0-LGqC2bRdgbbeld_uDOp89Y5CG19Vk',
    appId: '1:106631481866:web:9bc07d2b181a7d3bc8adf3',
    messagingSenderId: '106631481866',
    projectId: 'nikeapp-13704',
    authDomain: 'nikeapp-13704.firebaseapp.com',
    storageBucket: 'nikeapp-13704.firebasestorage.app',
    measurementId: 'G-H7ZD5KW8T6',
  );
}
